### ISSUE TITLE
Loss of Gene Symbol Cohesion across BXD Expression Datasets

### ISSUE THREAD

**Issue by MulliganLab** [genenetwork/genenetwork1#59] opened 2019-04-25 16:35 UTC
The Symbol is no longer matching across Datasets. In example 1 the Gene (GeneID) and Verify (UCSC) work and link to the most current symbol (Ncapd2). However, different and out-of-date symbols shown for some datasets. In example 2 the Gene link does not work but the Verify link does point to the current gene (Lcorl).

Example 1: _**Ncapd2**_
**_2810406C15Rik_** [VCU BXD NAc Sal   M430 2.0 (Oct07) RMA::1430010_at]
**_Cnap1_** [VCU BXD NAc Sal M430 2.0 (Oct07) RMA::VCU BXD PFC Sal M430 2.0 (Dec06) RMA::VCU BXD VTA Sal M430 2.0 (Jun09) RMA::1423847_at]
**_Ncapd2_** [INIA Hypothalamus Affy MoGene 1.0 ST (Nov10)::10547943]

Example 2: _**Lcorl**_
_**Mlr1**_[HBP Rosen Striatum M430V2 (Apr05) RMA Clean::1446571_at::1460063_at::1445552_at::VCU BXD NAc Sal M430 2.0 (Oct07) RMA::1460063_at::VCU BXD VTA Sal M430 2.0 (Jun09) RMA::1455260_at]
_**Lcorl**_ [HBP Rosen Striatum M430V2 (Apr05) RMA Clean::1439272_at::INIA Hypothalamus Affy MoGene 1.0 ST (Nov10)::10529923::VCU BXD NAc Sal   M430 2.0 (Oct07) RMA::1455686_at::1439272_at::VCU BXD PFC Sal M430 2.0 (Dec06) RMA::1439272_at]

**Comment by pjotrp** [comment] 2019-05-01 13:41
Thank you @MulliganLab: gene aliases need to be fixed in a robust fashion. @chfi has started work on this and we need to solve it.

**Comment by pjotrp** [comment] 2019-05-01 13:41
Note the problem is the same for GN2 and OPAR UIs.

**Comment by pjotrp** [comment] 2019-05-01 13:43
See https://github.com/genenetwork/genenetwork2/issues/364

**Comment by MulliganLab** [comment] 2019-05-01 14:03
Thank you for the update!
-M

Megan K. Mulligan, Ph.D.
Assistant Professor
Department of Genetics, Genomics and Informatics
University of Tennessee Health Science Center
71 S. Manassas St., Rm. 409, Memphis TN 38163 USA
Telephone: (901) 448-3548 Mobile: (512) 680-2386
email 1: mmulliga@uthsc.edu email 2: mulliganmk@gmail.com

**Comment by pjotrp** [comment] 2021-02-05 21:53
I think this is solved in GN2.

**Closed by pjotrp** 2021-02-05 21:53 UTC
Labels: enhancement
